# Generated by Django 5.2.4 on 2025-07-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_service_alter_customuser_role_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='services',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
