# Generated by Django 5.2.4 on 2025-07-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_team_services_delete_service'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='services', to='services.service'),
        ),
    ]
