# Generated by Django 5.2.4 on 2025-07-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(help_text='e.g., Ward 4, Room 201B', max_length=255)),
                ('doctor_description', models.TextField(blank=True, help_text='Description for doctors.')),
                ('staff_description', models.TextField(blank=True, help_text='Description for general staff.')),
                ('admin_description', models.TextField(blank=True, help_text='Internal description for administrators.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROCESS', 'In Process'), ('PROCESS_ENDING', 'Process Ending'), ('CLOSED', 'Closed')], db_index=True, default='PENDING', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Optional image related to the alert.', null=True, upload_to='alert_images/')),
                ('created_time', models.DateTimeField(blank=True)),
                ('recieved_time', models.DateTimeField(auto_now_add=True)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('in_process_date', models.DateTimeField(blank=True, null=True)),
                ('process_ending_date', models.DateTimeField(blank=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
