# Generated by Django 5.2.4 on 2025-07-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_assigned_team_alert_creator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='admin_description',
            field=models.TextField(blank=True, help_text='Internal description for administrators.', null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='doctor_description',
            field=models.TextField(blank=True, help_text='Description for doctors.', null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='staff_description',
            field=models.TextField(blank=True, help_text='Description for general staff.', null=True),
        ),
    ]
